# Generated by Django 3.0.7 on 2023-04-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0003_alter_registration_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('cat_image', models.ImageField(upload_to='category/')),
            ],
        ),
    ]
