# Generated by Django 3.0.7 on 2023-04-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pro_image', models.ImageField(upload_to='product/')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('desc', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.Category')),
            ],
        ),
    ]
